/**
 * AI-Generated Unique Insight — Layer 1 of the Differentiation Engine.
 *
 * Renders a unique prose paragraph generated by Gemini AI.
 * Each page gets a different paragraph that Google cannot cluster.
 */

import { Sparkles } from "lucide-react";

export function AIInsight({
  insight,
  label,
}: {
  insight: string | null;
  label?: string;
}) {
  if (!insight) return null;

  return (
    <div className="rounded-xl border border-[#2F5EA8]/10 bg-gradient-to-br from-[#2F5EA8]/[0.03] to-transparent p-6">
      <div className="flex items-center gap-2 mb-3">
        <Sparkles className="h-4 w-4 text-[#2F5EA8]" />
        <span className="text-xs font-semibold uppercase tracking-wider text-[#2F5EA8]">
          {label || "AI Analysis"}
        </span>
      </div>
      <p className="text-sm leading-relaxed text-[var(--text-secondary)]">
        {insight}
      </p>
    </div>
  );
}
