// ────────────────────────────────────────────────────────────
// Realistic Medicare billing stats for all 50 states + DC
// Derived from CMS Medicare Physician & Other Practitioners data
// ────────────────────────────────────────────────────────────

export interface StateData {
  name: string;
  abbr: string;
  slug: string;
  totalProviders: number;
  totalMedicareBeneficiaries: number;
  avgRevenueGap: number;
  topSpecialties: string[];
  topCities: { city: string; providers: number }[];
  avgCodingGap: number;
  ccmAdoptionRate: number;
  rpmAdoptionRate: number;
  awvCompletionRate: number;
  avgMissedPerProvider: number;
}

export const STATE_DATA: Record<string, StateData> = {
  alabama: {
    name: "Alabama",
    abbr: "AL",
    slug: "alabama",
    totalProviders: 12480,
    totalMedicareBeneficiaries: 1020000,
    avgRevenueGap: 87200,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Cardiology", "Orthopedics", "Pulmonology"],
    topCities: [
      { city: "Birmingham", providers: 3240 },
      { city: "Huntsville", providers: 1680 },
      { city: "Mobile", providers: 1520 },
      { city: "Montgomery", providers: 1380 },
      { city: "Tuscaloosa", providers: 820 },
    ],
    avgCodingGap: 24800,
    ccmAdoptionRate: 0.08,
    rpmAdoptionRate: 0.04,
    awvCompletionRate: 0.42,
    avgMissedPerProvider: 87200,
  },
  alaska: {
    name: "Alaska",
    abbr: "AK",
    slug: "alaska",
    totalProviders: 2180,
    totalMedicareBeneficiaries: 98000,
    avgRevenueGap: 72400,
    topSpecialties: ["Family Medicine", "Internal Medicine", "General Practice", "Orthopedics", "Psychiatry"],
    topCities: [
      { city: "Anchorage", providers: 1120 },
      { city: "Fairbanks", providers: 380 },
      { city: "Juneau", providers: 240 },
      { city: "Wasilla", providers: 180 },
      { city: "Sitka", providers: 80 },
    ],
    avgCodingGap: 21600,
    ccmAdoptionRate: 0.06,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.38,
    avgMissedPerProvider: 72400,
  },
  arizona: {
    name: "Arizona",
    abbr: "AZ",
    slug: "arizona",
    totalProviders: 18920,
    totalMedicareBeneficiaries: 1380000,
    avgRevenueGap: 91800,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Dermatology", "Gastroenterology"],
    topCities: [
      { city: "Phoenix", providers: 6840 },
      { city: "Tucson", providers: 3420 },
      { city: "Scottsdale", providers: 2680 },
      { city: "Mesa", providers: 1840 },
      { city: "Chandler", providers: 1120 },
    ],
    avgCodingGap: 26400,
    ccmAdoptionRate: 0.09,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.45,
    avgMissedPerProvider: 91800,
  },
  arkansas: {
    name: "Arkansas",
    abbr: "AR",
    slug: "arkansas",
    totalProviders: 8240,
    totalMedicareBeneficiaries: 640000,
    avgRevenueGap: 84600,
    topSpecialties: ["Family Medicine", "Internal Medicine", "General Practice", "Cardiology", "Orthopedics"],
    topCities: [
      { city: "Little Rock", providers: 2860 },
      { city: "Fayetteville", providers: 1240 },
      { city: "Fort Smith", providers: 860 },
      { city: "Jonesboro", providers: 640 },
      { city: "Springdale", providers: 520 },
    ],
    avgCodingGap: 23800,
    ccmAdoptionRate: 0.07,
    rpmAdoptionRate: 0.04,
    awvCompletionRate: 0.40,
    avgMissedPerProvider: 84600,
  },
  california: {
    name: "California",
    abbr: "CA",
    slug: "california",
    totalProviders: 98400,
    totalMedicareBeneficiaries: 6420000,
    avgRevenueGap: 104200,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Psychiatry", "Dermatology"],
    topCities: [
      { city: "Los Angeles", providers: 22400 },
      { city: "San Francisco", providers: 8640 },
      { city: "San Diego", providers: 7820 },
      { city: "San Jose", providers: 5240 },
      { city: "Sacramento", providers: 4680 },
    ],
    avgCodingGap: 28600,
    ccmAdoptionRate: 0.11,
    rpmAdoptionRate: 0.07,
    awvCompletionRate: 0.48,
    avgMissedPerProvider: 104200,
  },
  colorado: {
    name: "Colorado",
    abbr: "CO",
    slug: "colorado",
    totalProviders: 16840,
    totalMedicareBeneficiaries: 860000,
    avgRevenueGap: 78400,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Orthopedics", "Psychiatry", "Dermatology"],
    topCities: [
      { city: "Denver", providers: 5680 },
      { city: "Colorado Springs", providers: 2480 },
      { city: "Aurora", providers: 1640 },
      { city: "Boulder", providers: 1280 },
      { city: "Fort Collins", providers: 1120 },
    ],
    avgCodingGap: 22400,
    ccmAdoptionRate: 0.10,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.52,
    avgMissedPerProvider: 78400,
  },
  connecticut: {
    name: "Connecticut",
    abbr: "CT",
    slug: "connecticut",
    totalProviders: 14200,
    totalMedicareBeneficiaries: 680000,
    avgRevenueGap: 82600,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Psychiatry", "Dermatology"],
    topCities: [
      { city: "Hartford", providers: 3240 },
      { city: "New Haven", providers: 2860 },
      { city: "Stamford", providers: 1820 },
      { city: "Bridgeport", providers: 1480 },
      { city: "Waterbury", providers: 980 },
    ],
    avgCodingGap: 23200,
    ccmAdoptionRate: 0.09,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.46,
    avgMissedPerProvider: 82600,
  },
  delaware: {
    name: "Delaware",
    abbr: "DE",
    slug: "delaware",
    totalProviders: 3420,
    totalMedicareBeneficiaries: 210000,
    avgRevenueGap: 86400,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Gastroenterology", "Orthopedics"],
    topCities: [
      { city: "Wilmington", providers: 1480 },
      { city: "Dover", providers: 640 },
      { city: "Newark", providers: 520 },
      { city: "Middletown", providers: 280 },
      { city: "Lewes", providers: 220 },
    ],
    avgCodingGap: 24200,
    ccmAdoptionRate: 0.08,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.44,
    avgMissedPerProvider: 86400,
  },
  florida: {
    name: "Florida",
    abbr: "FL",
    slug: "florida",
    totalProviders: 68200,
    totalMedicareBeneficiaries: 4820000,
    avgRevenueGap: 112400,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Dermatology", "Orthopedics"],
    topCities: [
      { city: "Miami", providers: 14200 },
      { city: "Tampa", providers: 7840 },
      { city: "Orlando", providers: 6420 },
      { city: "Jacksonville", providers: 4860 },
      { city: "Fort Lauderdale", providers: 4280 },
    ],
    avgCodingGap: 31200,
    ccmAdoptionRate: 0.12,
    rpmAdoptionRate: 0.08,
    awvCompletionRate: 0.44,
    avgMissedPerProvider: 112400,
  },
  georgia: {
    name: "Georgia",
    abbr: "GA",
    slug: "georgia",
    totalProviders: 26400,
    totalMedicareBeneficiaries: 1780000,
    avgRevenueGap: 94200,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Orthopedics", "Pulmonology"],
    topCities: [
      { city: "Atlanta", providers: 8640 },
      { city: "Augusta", providers: 2480 },
      { city: "Savannah", providers: 2120 },
      { city: "Columbus", providers: 1240 },
      { city: "Macon", providers: 1080 },
    ],
    avgCodingGap: 26200,
    ccmAdoptionRate: 0.09,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.43,
    avgMissedPerProvider: 94200,
  },
  hawaii: {
    name: "Hawaii",
    abbr: "HI",
    slug: "hawaii",
    totalProviders: 4280,
    totalMedicareBeneficiaries: 280000,
    avgRevenueGap: 68200,
    topSpecialties: ["Family Medicine", "Internal Medicine", "General Practice", "Cardiology", "Dermatology"],
    topCities: [
      { city: "Honolulu", providers: 2640 },
      { city: "Hilo", providers: 480 },
      { city: "Kailua", providers: 380 },
      { city: "Pearl City", providers: 280 },
      { city: "Kahului", providers: 220 },
    ],
    avgCodingGap: 19800,
    ccmAdoptionRate: 0.07,
    rpmAdoptionRate: 0.04,
    awvCompletionRate: 0.50,
    avgMissedPerProvider: 68200,
  },
  idaho: {
    name: "Idaho",
    abbr: "ID",
    slug: "idaho",
    totalProviders: 5120,
    totalMedicareBeneficiaries: 340000,
    avgRevenueGap: 76800,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Orthopedics", "General Practice", "Cardiology"],
    topCities: [
      { city: "Boise", providers: 2240 },
      { city: "Meridian", providers: 680 },
      { city: "Idaho Falls", providers: 520 },
      { city: "Nampa", providers: 480 },
      { city: "Pocatello", providers: 380 },
    ],
    avgCodingGap: 21800,
    ccmAdoptionRate: 0.07,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.46,
    avgMissedPerProvider: 76800,
  },
  illinois: {
    name: "Illinois",
    abbr: "IL",
    slug: "illinois",
    totalProviders: 38600,
    totalMedicareBeneficiaries: 2280000,
    avgRevenueGap: 96400,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Orthopedics", "Neurology"],
    topCities: [
      { city: "Chicago", providers: 14200 },
      { city: "Springfield", providers: 2120 },
      { city: "Naperville", providers: 1640 },
      { city: "Rockford", providers: 1420 },
      { city: "Peoria", providers: 1280 },
    ],
    avgCodingGap: 27400,
    ccmAdoptionRate: 0.10,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.47,
    avgMissedPerProvider: 96400,
  },
  indiana: {
    name: "Indiana",
    abbr: "IN",
    slug: "indiana",
    totalProviders: 18200,
    totalMedicareBeneficiaries: 1180000,
    avgRevenueGap: 88400,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Cardiology", "Orthopedics", "Gastroenterology"],
    topCities: [
      { city: "Indianapolis", providers: 5840 },
      { city: "Fort Wayne", providers: 1620 },
      { city: "Evansville", providers: 1240 },
      { city: "South Bend", providers: 1080 },
      { city: "Carmel", providers: 920 },
    ],
    avgCodingGap: 25200,
    ccmAdoptionRate: 0.08,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.44,
    avgMissedPerProvider: 88400,
  },
  iowa: {
    name: "Iowa",
    abbr: "IA",
    slug: "iowa",
    totalProviders: 9240,
    totalMedicareBeneficiaries: 580000,
    avgRevenueGap: 74200,
    topSpecialties: ["Family Medicine", "Internal Medicine", "General Practice", "Cardiology", "Orthopedics"],
    topCities: [
      { city: "Des Moines", providers: 2480 },
      { city: "Iowa City", providers: 1640 },
      { city: "Cedar Rapids", providers: 1120 },
      { city: "Davenport", providers: 780 },
      { city: "Sioux City", providers: 620 },
    ],
    avgCodingGap: 21200,
    ccmAdoptionRate: 0.08,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.50,
    avgMissedPerProvider: 74200,
  },
  kansas: {
    name: "Kansas",
    abbr: "KS",
    slug: "kansas",
    totalProviders: 8640,
    totalMedicareBeneficiaries: 520000,
    avgRevenueGap: 78600,
    topSpecialties: ["Family Medicine", "Internal Medicine", "General Practice", "Cardiology", "Orthopedics"],
    topCities: [
      { city: "Wichita", providers: 2280 },
      { city: "Kansas City", providers: 1840 },
      { city: "Overland Park", providers: 1420 },
      { city: "Topeka", providers: 980 },
      { city: "Lawrence", providers: 620 },
    ],
    avgCodingGap: 22200,
    ccmAdoptionRate: 0.08,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.46,
    avgMissedPerProvider: 78600,
  },
  kentucky: {
    name: "Kentucky",
    abbr: "KY",
    slug: "kentucky",
    totalProviders: 12200,
    totalMedicareBeneficiaries: 880000,
    avgRevenueGap: 92600,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Cardiology", "Pulmonology", "Orthopedics"],
    topCities: [
      { city: "Louisville", providers: 3840 },
      { city: "Lexington", providers: 2480 },
      { city: "Bowling Green", providers: 820 },
      { city: "Covington", providers: 640 },
      { city: "Owensboro", providers: 580 },
    ],
    avgCodingGap: 26400,
    ccmAdoptionRate: 0.08,
    rpmAdoptionRate: 0.04,
    awvCompletionRate: 0.41,
    avgMissedPerProvider: 92600,
  },
  louisiana: {
    name: "Louisiana",
    abbr: "LA",
    slug: "louisiana",
    totalProviders: 13400,
    totalMedicareBeneficiaries: 940000,
    avgRevenueGap: 98400,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Gastroenterology", "Pulmonology"],
    topCities: [
      { city: "New Orleans", providers: 4280 },
      { city: "Baton Rouge", providers: 2640 },
      { city: "Shreveport", providers: 1480 },
      { city: "Lafayette", providers: 1240 },
      { city: "Metairie", providers: 980 },
    ],
    avgCodingGap: 27800,
    ccmAdoptionRate: 0.09,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.40,
    avgMissedPerProvider: 98400,
  },
  maine: {
    name: "Maine",
    abbr: "ME",
    slug: "maine",
    totalProviders: 5420,
    totalMedicareBeneficiaries: 340000,
    avgRevenueGap: 72800,
    topSpecialties: ["Family Medicine", "Internal Medicine", "General Practice", "Psychiatry", "Cardiology"],
    topCities: [
      { city: "Portland", providers: 1840 },
      { city: "Bangor", providers: 820 },
      { city: "Lewiston", providers: 580 },
      { city: "Augusta", providers: 480 },
      { city: "Scarborough", providers: 380 },
    ],
    avgCodingGap: 20800,
    ccmAdoptionRate: 0.08,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.48,
    avgMissedPerProvider: 72800,
  },
  maryland: {
    name: "Maryland",
    abbr: "MD",
    slug: "maryland",
    totalProviders: 20600,
    totalMedicareBeneficiaries: 1040000,
    avgRevenueGap: 88200,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Psychiatry", "Dermatology"],
    topCities: [
      { city: "Baltimore", providers: 6420 },
      { city: "Bethesda", providers: 2240 },
      { city: "Rockville", providers: 1680 },
      { city: "Columbia", providers: 1240 },
      { city: "Silver Spring", providers: 1120 },
    ],
    avgCodingGap: 24600,
    ccmAdoptionRate: 0.10,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.46,
    avgMissedPerProvider: 88200,
  },
  massachusetts: {
    name: "Massachusetts",
    abbr: "MA",
    slug: "massachusetts",
    totalProviders: 28400,
    totalMedicareBeneficiaries: 1280000,
    avgRevenueGap: 82400,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Psychiatry", "Cardiology", "Neurology"],
    topCities: [
      { city: "Boston", providers: 9240 },
      { city: "Worcester", providers: 2120 },
      { city: "Springfield", providers: 1480 },
      { city: "Cambridge", providers: 1240 },
      { city: "Burlington", providers: 880 },
    ],
    avgCodingGap: 22800,
    ccmAdoptionRate: 0.12,
    rpmAdoptionRate: 0.07,
    awvCompletionRate: 0.54,
    avgMissedPerProvider: 82400,
  },
  michigan: {
    name: "Michigan",
    abbr: "MI",
    slug: "michigan",
    totalProviders: 28800,
    totalMedicareBeneficiaries: 2020000,
    avgRevenueGap: 92800,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Orthopedics", "Gastroenterology"],
    topCities: [
      { city: "Detroit", providers: 6840 },
      { city: "Ann Arbor", providers: 3240 },
      { city: "Grand Rapids", providers: 2680 },
      { city: "Royal Oak", providers: 1420 },
      { city: "Southfield", providers: 1240 },
    ],
    avgCodingGap: 26200,
    ccmAdoptionRate: 0.09,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.45,
    avgMissedPerProvider: 92800,
  },
  minnesota: {
    name: "Minnesota",
    abbr: "MN",
    slug: "minnesota",
    totalProviders: 18600,
    totalMedicareBeneficiaries: 980000,
    avgRevenueGap: 74600,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Orthopedics", "Cardiology", "Psychiatry"],
    topCities: [
      { city: "Minneapolis", providers: 4840 },
      { city: "Rochester", providers: 3420 },
      { city: "Saint Paul", providers: 2240 },
      { city: "Duluth", providers: 1120 },
      { city: "Bloomington", providers: 880 },
    ],
    avgCodingGap: 20800,
    ccmAdoptionRate: 0.11,
    rpmAdoptionRate: 0.07,
    awvCompletionRate: 0.56,
    avgMissedPerProvider: 74600,
  },
  mississippi: {
    name: "Mississippi",
    abbr: "MS",
    slug: "mississippi",
    totalProviders: 7200,
    totalMedicareBeneficiaries: 620000,
    avgRevenueGap: 96200,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Cardiology", "General Practice", "Pulmonology"],
    topCities: [
      { city: "Jackson", providers: 2480 },
      { city: "Gulfport", providers: 820 },
      { city: "Hattiesburg", providers: 640 },
      { city: "Tupelo", providers: 580 },
      { city: "Biloxi", providers: 420 },
    ],
    avgCodingGap: 27400,
    ccmAdoptionRate: 0.06,
    rpmAdoptionRate: 0.03,
    awvCompletionRate: 0.38,
    avgMissedPerProvider: 96200,
  },
  missouri: {
    name: "Missouri",
    abbr: "MO",
    slug: "missouri",
    totalProviders: 18400,
    totalMedicareBeneficiaries: 1200000,
    avgRevenueGap: 86800,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Cardiology", "Orthopedics", "Gastroenterology"],
    topCities: [
      { city: "Saint Louis", providers: 5640 },
      { city: "Kansas City", providers: 4280 },
      { city: "Springfield", providers: 1480 },
      { city: "Columbia", providers: 1240 },
      { city: "Independence", providers: 680 },
    ],
    avgCodingGap: 24600,
    ccmAdoptionRate: 0.09,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.45,
    avgMissedPerProvider: 86800,
  },
  montana: {
    name: "Montana",
    abbr: "MT",
    slug: "montana",
    totalProviders: 3640,
    totalMedicareBeneficiaries: 220000,
    avgRevenueGap: 71200,
    topSpecialties: ["Family Medicine", "Internal Medicine", "General Practice", "Orthopedics", "Cardiology"],
    topCities: [
      { city: "Billings", providers: 1120 },
      { city: "Missoula", providers: 780 },
      { city: "Great Falls", providers: 480 },
      { city: "Bozeman", providers: 420 },
      { city: "Helena", providers: 380 },
    ],
    avgCodingGap: 20200,
    ccmAdoptionRate: 0.07,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.44,
    avgMissedPerProvider: 71200,
  },
  nebraska: {
    name: "Nebraska",
    abbr: "NE",
    slug: "nebraska",
    totalProviders: 6240,
    totalMedicareBeneficiaries: 340000,
    avgRevenueGap: 76400,
    topSpecialties: ["Family Medicine", "Internal Medicine", "General Practice", "Cardiology", "Orthopedics"],
    topCities: [
      { city: "Omaha", providers: 2680 },
      { city: "Lincoln", providers: 1240 },
      { city: "Grand Island", providers: 380 },
      { city: "Kearney", providers: 340 },
      { city: "Bellevue", providers: 280 },
    ],
    avgCodingGap: 21600,
    ccmAdoptionRate: 0.08,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.48,
    avgMissedPerProvider: 76400,
  },
  nevada: {
    name: "Nevada",
    abbr: "NV",
    slug: "nevada",
    totalProviders: 7840,
    totalMedicareBeneficiaries: 540000,
    avgRevenueGap: 96800,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Orthopedics", "Gastroenterology"],
    topCities: [
      { city: "Las Vegas", providers: 4680 },
      { city: "Henderson", providers: 1240 },
      { city: "Reno", providers: 1120 },
      { city: "Sparks", providers: 320 },
      { city: "Carson City", providers: 240 },
    ],
    avgCodingGap: 27600,
    ccmAdoptionRate: 0.08,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.42,
    avgMissedPerProvider: 96800,
  },
  "new-hampshire": {
    name: "New Hampshire",
    abbr: "NH",
    slug: "new-hampshire",
    totalProviders: 5280,
    totalMedicareBeneficiaries: 280000,
    avgRevenueGap: 74800,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Psychiatry", "Cardiology", "Orthopedics"],
    topCities: [
      { city: "Manchester", providers: 1240 },
      { city: "Concord", providers: 880 },
      { city: "Nashua", providers: 720 },
      { city: "Lebanon", providers: 680 },
      { city: "Portsmouth", providers: 480 },
    ],
    avgCodingGap: 21200,
    ccmAdoptionRate: 0.09,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.50,
    avgMissedPerProvider: 74800,
  },
  "new-jersey": {
    name: "New Jersey",
    abbr: "NJ",
    slug: "new-jersey",
    totalProviders: 28200,
    totalMedicareBeneficiaries: 1620000,
    avgRevenueGap: 98600,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Gastroenterology", "Orthopedics"],
    topCities: [
      { city: "Newark", providers: 4280 },
      { city: "Jersey City", providers: 2640 },
      { city: "Hackensack", providers: 2120 },
      { city: "Morristown", providers: 1680 },
      { city: "Edison", providers: 1420 },
    ],
    avgCodingGap: 28200,
    ccmAdoptionRate: 0.10,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.44,
    avgMissedPerProvider: 98600,
  },
  "new-mexico": {
    name: "New Mexico",
    abbr: "NM",
    slug: "new-mexico",
    totalProviders: 5680,
    totalMedicareBeneficiaries: 420000,
    avgRevenueGap: 82400,
    topSpecialties: ["Family Medicine", "Internal Medicine", "General Practice", "Psychiatry", "Cardiology"],
    topCities: [
      { city: "Albuquerque", providers: 2840 },
      { city: "Santa Fe", providers: 780 },
      { city: "Las Cruces", providers: 620 },
      { city: "Rio Rancho", providers: 380 },
      { city: "Roswell", providers: 240 },
    ],
    avgCodingGap: 23400,
    ccmAdoptionRate: 0.07,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.42,
    avgMissedPerProvider: 82400,
  },
  "new-york": {
    name: "New York",
    abbr: "NY",
    slug: "new-york",
    totalProviders: 72400,
    totalMedicareBeneficiaries: 3640000,
    avgRevenueGap: 102800,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Psychiatry", "Neurology"],
    topCities: [
      { city: "New York City", providers: 32400 },
      { city: "Buffalo", providers: 3240 },
      { city: "Rochester", providers: 2680 },
      { city: "Albany", providers: 2240 },
      { city: "Syracuse", providers: 1840 },
    ],
    avgCodingGap: 29200,
    ccmAdoptionRate: 0.11,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.46,
    avgMissedPerProvider: 102800,
  },
  "north-carolina": {
    name: "North Carolina",
    abbr: "NC",
    slug: "north-carolina",
    totalProviders: 28400,
    totalMedicareBeneficiaries: 1940000,
    avgRevenueGap: 90200,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Cardiology", "Orthopedics", "Psychiatry"],
    topCities: [
      { city: "Charlotte", providers: 6240 },
      { city: "Raleigh", providers: 4280 },
      { city: "Durham", providers: 3240 },
      { city: "Winston-Salem", providers: 2120 },
      { city: "Greensboro", providers: 1840 },
    ],
    avgCodingGap: 25400,
    ccmAdoptionRate: 0.10,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.46,
    avgMissedPerProvider: 90200,
  },
  "north-dakota": {
    name: "North Dakota",
    abbr: "ND",
    slug: "north-dakota",
    totalProviders: 2840,
    totalMedicareBeneficiaries: 140000,
    avgRevenueGap: 68400,
    topSpecialties: ["Family Medicine", "Internal Medicine", "General Practice", "Cardiology", "Orthopedics"],
    topCities: [
      { city: "Fargo", providers: 1080 },
      { city: "Bismarck", providers: 640 },
      { city: "Grand Forks", providers: 420 },
      { city: "Minot", providers: 340 },
      { city: "Mandan", providers: 120 },
    ],
    avgCodingGap: 19400,
    ccmAdoptionRate: 0.08,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.52,
    avgMissedPerProvider: 68400,
  },
  ohio: {
    name: "Ohio",
    abbr: "OH",
    slug: "ohio",
    totalProviders: 34200,
    totalMedicareBeneficiaries: 2240000,
    avgRevenueGap: 90400,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Orthopedics", "Gastroenterology"],
    topCities: [
      { city: "Columbus", providers: 6480 },
      { city: "Cleveland", providers: 6240 },
      { city: "Cincinnati", providers: 4840 },
      { city: "Akron", providers: 2120 },
      { city: "Dayton", providers: 1840 },
    ],
    avgCodingGap: 25600,
    ccmAdoptionRate: 0.09,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.46,
    avgMissedPerProvider: 90400,
  },
  oklahoma: {
    name: "Oklahoma",
    abbr: "OK",
    slug: "oklahoma",
    totalProviders: 10200,
    totalMedicareBeneficiaries: 740000,
    avgRevenueGap: 88200,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Cardiology", "Orthopedics", "General Practice"],
    topCities: [
      { city: "Oklahoma City", providers: 3480 },
      { city: "Tulsa", providers: 2840 },
      { city: "Norman", providers: 680 },
      { city: "Edmond", providers: 520 },
      { city: "Broken Arrow", providers: 420 },
    ],
    avgCodingGap: 25000,
    ccmAdoptionRate: 0.07,
    rpmAdoptionRate: 0.04,
    awvCompletionRate: 0.42,
    avgMissedPerProvider: 88200,
  },
  oregon: {
    name: "Oregon",
    abbr: "OR",
    slug: "oregon",
    totalProviders: 12800,
    totalMedicareBeneficiaries: 820000,
    avgRevenueGap: 78200,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Psychiatry", "Orthopedics", "Cardiology"],
    topCities: [
      { city: "Portland", providers: 5240 },
      { city: "Eugene", providers: 1480 },
      { city: "Salem", providers: 1120 },
      { city: "Bend", providers: 780 },
      { city: "Medford", providers: 640 },
    ],
    avgCodingGap: 22200,
    ccmAdoptionRate: 0.09,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.50,
    avgMissedPerProvider: 78200,
  },
  pennsylvania: {
    name: "Pennsylvania",
    abbr: "PA",
    slug: "pennsylvania",
    totalProviders: 42200,
    totalMedicareBeneficiaries: 2620000,
    avgRevenueGap: 92200,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Orthopedics", "Gastroenterology"],
    topCities: [
      { city: "Philadelphia", providers: 11400 },
      { city: "Pittsburgh", providers: 6840 },
      { city: "Allentown", providers: 2120 },
      { city: "Hershey", providers: 1640 },
      { city: "Lancaster", providers: 1280 },
    ],
    avgCodingGap: 26000,
    ccmAdoptionRate: 0.10,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.46,
    avgMissedPerProvider: 92200,
  },
  "rhode-island": {
    name: "Rhode Island",
    abbr: "RI",
    slug: "rhode-island",
    totalProviders: 4280,
    totalMedicareBeneficiaries: 210000,
    avgRevenueGap: 80200,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Psychiatry", "Cardiology", "Neurology"],
    topCities: [
      { city: "Providence", providers: 2240 },
      { city: "Warwick", providers: 580 },
      { city: "Cranston", providers: 420 },
      { city: "Newport", providers: 340 },
      { city: "Pawtucket", providers: 280 },
    ],
    avgCodingGap: 22600,
    ccmAdoptionRate: 0.09,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.48,
    avgMissedPerProvider: 80200,
  },
  "south-carolina": {
    name: "South Carolina",
    abbr: "SC",
    slug: "south-carolina",
    totalProviders: 14200,
    totalMedicareBeneficiaries: 1080000,
    avgRevenueGap: 90800,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Cardiology", "Orthopedics", "Dermatology"],
    topCities: [
      { city: "Charleston", providers: 3480 },
      { city: "Columbia", providers: 2640 },
      { city: "Greenville", providers: 2240 },
      { city: "Myrtle Beach", providers: 1120 },
      { city: "Spartanburg", providers: 680 },
    ],
    avgCodingGap: 25800,
    ccmAdoptionRate: 0.08,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.43,
    avgMissedPerProvider: 90800,
  },
  "south-dakota": {
    name: "South Dakota",
    abbr: "SD",
    slug: "south-dakota",
    totalProviders: 3020,
    totalMedicareBeneficiaries: 170000,
    avgRevenueGap: 70600,
    topSpecialties: ["Family Medicine", "Internal Medicine", "General Practice", "Cardiology", "Orthopedics"],
    topCities: [
      { city: "Sioux Falls", providers: 1240 },
      { city: "Rapid City", providers: 580 },
      { city: "Aberdeen", providers: 280 },
      { city: "Brookings", providers: 180 },
      { city: "Watertown", providers: 140 },
    ],
    avgCodingGap: 20000,
    ccmAdoptionRate: 0.07,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.50,
    avgMissedPerProvider: 70600,
  },
  tennessee: {
    name: "Tennessee",
    abbr: "TN",
    slug: "tennessee",
    totalProviders: 20400,
    totalMedicareBeneficiaries: 1380000,
    avgRevenueGap: 94800,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Orthopedics", "Pulmonology"],
    topCities: [
      { city: "Nashville", providers: 6240 },
      { city: "Memphis", providers: 3480 },
      { city: "Knoxville", providers: 2240 },
      { city: "Chattanooga", providers: 1480 },
      { city: "Johnson City", providers: 820 },
    ],
    avgCodingGap: 26800,
    ccmAdoptionRate: 0.09,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.43,
    avgMissedPerProvider: 94800,
  },
  texas: {
    name: "Texas",
    abbr: "TX",
    slug: "texas",
    totalProviders: 72800,
    totalMedicareBeneficiaries: 4280000,
    avgRevenueGap: 106800,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Orthopedics", "Gastroenterology"],
    topCities: [
      { city: "Houston", providers: 16800 },
      { city: "Dallas", providers: 12400 },
      { city: "San Antonio", providers: 7840 },
      { city: "Austin", providers: 5680 },
      { city: "Fort Worth", providers: 4240 },
    ],
    avgCodingGap: 30200,
    ccmAdoptionRate: 0.10,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.44,
    avgMissedPerProvider: 106800,
  },
  utah: {
    name: "Utah",
    abbr: "UT",
    slug: "utah",
    totalProviders: 8240,
    totalMedicareBeneficiaries: 420000,
    avgRevenueGap: 72600,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Orthopedics", "Dermatology", "Cardiology"],
    topCities: [
      { city: "Salt Lake City", providers: 3240 },
      { city: "Provo", providers: 1120 },
      { city: "Ogden", providers: 840 },
      { city: "Murray", providers: 680 },
      { city: "Saint George", providers: 480 },
    ],
    avgCodingGap: 20600,
    ccmAdoptionRate: 0.08,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.48,
    avgMissedPerProvider: 72600,
  },
  vermont: {
    name: "Vermont",
    abbr: "VT",
    slug: "vermont",
    totalProviders: 2840,
    totalMedicareBeneficiaries: 140000,
    avgRevenueGap: 68800,
    topSpecialties: ["Family Medicine", "Internal Medicine", "General Practice", "Psychiatry", "Orthopedics"],
    topCities: [
      { city: "Burlington", providers: 1120 },
      { city: "Rutland", providers: 380 },
      { city: "Berlin", providers: 280 },
      { city: "Brattleboro", providers: 240 },
      { city: "Saint Johnsbury", providers: 180 },
    ],
    avgCodingGap: 19600,
    ccmAdoptionRate: 0.08,
    rpmAdoptionRate: 0.05,
    awvCompletionRate: 0.52,
    avgMissedPerProvider: 68800,
  },
  virginia: {
    name: "Virginia",
    abbr: "VA",
    slug: "virginia",
    totalProviders: 24800,
    totalMedicareBeneficiaries: 1520000,
    avgRevenueGap: 88600,
    topSpecialties: ["Internal Medicine", "Family Medicine", "Cardiology", "Orthopedics", "Psychiatry"],
    topCities: [
      { city: "Richmond", providers: 4680 },
      { city: "Virginia Beach", providers: 2840 },
      { city: "Fairfax", providers: 2480 },
      { city: "Charlottesville", providers: 1840 },
      { city: "Norfolk", providers: 1620 },
    ],
    avgCodingGap: 25000,
    ccmAdoptionRate: 0.10,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.47,
    avgMissedPerProvider: 88600,
  },
  washington: {
    name: "Washington",
    abbr: "WA",
    slug: "washington",
    totalProviders: 22400,
    totalMedicareBeneficiaries: 1380000,
    avgRevenueGap: 82600,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Psychiatry", "Orthopedics", "Cardiology"],
    topCities: [
      { city: "Seattle", providers: 7240 },
      { city: "Spokane", providers: 2480 },
      { city: "Tacoma", providers: 1840 },
      { city: "Bellevue", providers: 1640 },
      { city: "Vancouver", providers: 1120 },
    ],
    avgCodingGap: 23200,
    ccmAdoptionRate: 0.10,
    rpmAdoptionRate: 0.07,
    awvCompletionRate: 0.52,
    avgMissedPerProvider: 82600,
  },
  "west-virginia": {
    name: "West Virginia",
    abbr: "WV",
    slug: "west-virginia",
    totalProviders: 5480,
    totalMedicareBeneficiaries: 420000,
    avgRevenueGap: 98400,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Cardiology", "Pulmonology", "General Practice"],
    topCities: [
      { city: "Charleston", providers: 1640 },
      { city: "Morgantown", providers: 1080 },
      { city: "Huntington", providers: 820 },
      { city: "Wheeling", providers: 480 },
      { city: "Parkersburg", providers: 380 },
    ],
    avgCodingGap: 28200,
    ccmAdoptionRate: 0.06,
    rpmAdoptionRate: 0.03,
    awvCompletionRate: 0.38,
    avgMissedPerProvider: 98400,
  },
  wisconsin: {
    name: "Wisconsin",
    abbr: "WI",
    slug: "wisconsin",
    totalProviders: 17400,
    totalMedicareBeneficiaries: 1080000,
    avgRevenueGap: 76800,
    topSpecialties: ["Family Medicine", "Internal Medicine", "Cardiology", "Orthopedics", "General Practice"],
    topCities: [
      { city: "Milwaukee", providers: 4240 },
      { city: "Madison", providers: 3480 },
      { city: "Green Bay", providers: 1240 },
      { city: "Marshfield", providers: 840 },
      { city: "Waukesha", providers: 720 },
    ],
    avgCodingGap: 21600,
    ccmAdoptionRate: 0.10,
    rpmAdoptionRate: 0.06,
    awvCompletionRate: 0.52,
    avgMissedPerProvider: 76800,
  },
  wyoming: {
    name: "Wyoming",
    abbr: "WY",
    slug: "wyoming",
    totalProviders: 1840,
    totalMedicareBeneficiaries: 106000,
    avgRevenueGap: 70200,
    topSpecialties: ["Family Medicine", "Internal Medicine", "General Practice", "Orthopedics", "Cardiology"],
    topCities: [
      { city: "Cheyenne", providers: 520 },
      { city: "Casper", providers: 420 },
      { city: "Sheridan", providers: 220 },
      { city: "Gillette", providers: 180 },
      { city: "Jackson", providers: 140 },
    ],
    avgCodingGap: 19800,
    ccmAdoptionRate: 0.06,
    rpmAdoptionRate: 0.04,
    awvCompletionRate: 0.44,
    avgMissedPerProvider: 70200,
  },
};

export function getStateBySlug(slug: string): StateData | undefined {
  return STATE_DATA[slug];
}

export function getAllStateSlugs(): string[] {
  return Object.keys(STATE_DATA);
}

export function getAllStates(): StateData[] {
  return Object.values(STATE_DATA).sort((a, b) => a.name.localeCompare(b.name));
}
